### ISSUE TITLE
There are no build instructions. 

### ISSUE THREAD

**Issue by ZiCog** [parallaxinc/PropBASIC#1]
There are no build instructions.

The following works on Debian though:

```
$ git clone https://github.com/parallaxinc/PropBASIC.git
$ cd PropBASIC/src
$ fpc  -opropbasic PropBasic.lpr
```

**Comment by pmrobert** [comment]
Thanks for that, it certainly makes building it from my editor of choice easier. To be fair, I'm not sure Bean ever stated or intended it to be built on anything other than a Lazarus environment - which does work nicely.

**Comment by bweir** [comment]
Ah, I had set up the build but never put instructions for it. I'll slap something together.

**Comment by bweir** [comment]
Added!
